server:
  port: 8001

spring:
  application:
    name: spring_cloud_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javadriven/spring_cloud_config
          search-paths: ConfigData
      uri: http://localhost:8001
