server:
  port: 8001

spring:
  application:
    name: lucky-world
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javadriven/spring_cloud_config
          search-paths: ConfigData
      uri: http://localhost:8001
